SELECT *
FROM EMP;

SELECT COMM, IFNULL(COMM, 0) RESULT
FROM EMP;

SELECT COMM, IF(COMM, 'yes', 'no') RESULT
FROM EMP;

SELECT DEPTNO, IF(DEPTNO = 20, 'dept-20', 'other') RESULT
FROM EMP;

SELECT DEPTNO,
       IF(DEPTNO = 10, 'dept-10',
          IF(DEPTNO = 20, 'dept-20',
             IF(DEPTNO = 30, 'dept-30', 'dept-40'))) RESULT
FROM EMP;

