-- 列出所有员工信息。
SELECT * FROM EMP;
-- 列出所有部门的名称和所在地。
SELECT DNAME, LOC FROM DEPT;
-- 列出所有员工名，列名显示'EMP_NAME'。
SELECT ENAME AS EMP_NAME FROM EMP;
-- 列出两遍全部部门名，第一列起名'COL_A'，第二列'COL_B'。
SELECT DNAME 'COL_A', DNAME 'COL_B' FROM DEPT;
-- 列出所有员工名和他的补助情况 `YES` 或 `NO`。
SELECT ENAME, IF(COMM != 0, 'YES', IF(COMM = 0, 'YES', 'NO'))RESULT FROM EMP;
-- 列出所有员工名和他的月总收入。
SELECT ENAME, IF(COMM, SAL + COMM, SAL) RESULT FROM EMP;
-- 列出公司的所有职位。
SELECT DISTINCT JOB FROM EMP;
-- 列出工资大于1500的所有员工信息。
SELECT * FROM EMP WHERE SAL > 1500;
-- 列出工资大于1500的办事员。
SELECT ENAME FROM EMP WHERE SAL > 1500 AND JOB = 'CLERK';
-- 列出所有办事员以及工资大于1500的其他员工。
SELECT ENAME FROM EMP WHERE JOB = 'CLERK' OR SAL + IFNULL(COMM, 0) > 1500;
-- 列出所有不是办事员的员工。
SELECT ENAME FROM EMP WHERE JOB != 'CLERK';
-- 列出所有被补助人员信息。
SELECT * FROM EMP WHERE COMM IS NOT NULL;
-- 列出编号在7499和7654之间的所有员工信息。
SELECT * FROM EMP WHERE EMPNO BETWEEN 7499 AND 7654;
-- 列出编号为7499和7654的两个员工信息，不许用OR。
SELECT * FROM EMP WHERE EMPNO IN (7499, 7654);
-- 列出工资在0-2000或者3000以上的员工信息。
SELECT * FROM EMP WHERE SAL NOT BETWEEN 2000 AND 3000;
-- 列出所有姓名为S开头的员工信息。
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
-- 列出所有姓名为S开头H结尾的员工信息。
SELECT * FROM EMP WHERE ENAME LIKE 'S%H';
-- 列出所有姓名中带S的员工信息。
SELECT * FROM EMP WHERE ENAME LIKE '%S%';
-- 列出所有姓名中第二位为L的员工信息。
SELECT * FROM EMP WHERE ENAME LIKE '_L%';
-- 列出所有姓名中不带S的员工信息。
SELECT * FROM EMP WHERE ENAME NOT LIKE '%S%';
-- 列出所有姓名中带单引号的员工信息。
SELECT * FROM EMP WHERE ENAME LIKE '%''%';
-- 列出所有姓名中带%号的员工信息。
SELECT * FROM EMP WHERE ENAME LIKE '%@%%' ESCAPE '@';
-- 列出每个部门每个月一共发出的工资数。
SELECT DEPTNO, SUM(SAL) + SUM(IFNULL(COMM, 0)) RESULT FROM EMP GROUP BY DEPTNO;
-- 列出和MARTIN工资一样的员工信息。
SELECT * FROM EMP WHERE SAL + IFNULL(COMM, 0) = (SELECT SAL + IFNULL(COMM, 0) FROM EMP WHERE ENAME = 'MARTIN');
-- 列出比SMITH和WARD工资都高的所有员工信息。
SELECT * FROM EMP WHERE SAL + IFNULL(COMM, 0) > ALL (SELECT SAL + IFNULL(COMM, 0) FROM EMP WHERE ENAME IN ('SMITH', 'WARD'));
-- 列出工资比10部门所有人工资要高的所有员工信息。
SELECT * FROM EMP WHERE SAL + IFNULL(COMM, 0) > ALL (SELECT SAL + IFNULL(COMM, 0) FROM EMP WHERE DEPTNO = 10);
-- 列出工资比10部门某些人工资要高的所有员工信息。
SELECT * FROM EMP WHERE SAL + IFNULL(COMM, 0) > ANY (SELECT SAL + IFNULL(COMM, 0) FROM EMP WHERE DEPTNO = 10);
-- 列出工资和10部门某些人工资一样的所有员工信息。
SELECT * FROM EMP WHERE SAL + IFNULL(COMM, 0) = SOME (SELECT SAL + IFNULL(COMM, 0) FROM EMP WHERE DEPTNO = 10);
-- 列出存在员工的部门，要求使用IN。
SELECT DEPTNO, DNAME FROM DEPT WHERE DEPTNO IN(SELECT DEPTNO FROM EMP);
-- 列出不存在员工的部门，要求使用EXISTS。
SELECT DEPTNO, DNAME FROM DEPT WHERE NOT EXISTS(SELECT 1 FROM EMP WHERE EMP.DEPTNO = DEPT.DEPTNO);
-- 列出所有员工信息和所有部门信息;
SELECT * FROM EMP JOIN DEPT D ON EMP.DEPTNO = D.DEPTNO;
-- 列出所有员工信息及所在部门信息，员工无部门，新加一列显示'待定'。
SELECT *, IFNULL(E.DEPTNO, '待定') RESULT FROM EMP E LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
-- 列出所有部门信息及其员工信息，部门无员工，新加一列显示'空部门'。
SELECT *, IFNULL(E.DEPTNO, '空部门') RESULT FROM EMP E RIGHT JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
-- 列出所有正式员工姓名及其所在部门。
SELECT ENAME, D.DEPTNO FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
-- 列出所有工资大于1500的员工以及所在部门名。
SELECT ENAME, DNAME FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE SAL > 1500;
-- 列出所有员工的姓名，工资，及其工资等级。
SELECT ENAME, SAL, IF(SAL < 1000, '一等', IF(SAL < 2000, '二等', IF(SAL < 3000, '三等', '四等'))) SALARYGRADE FROM EMP;
-- 列出所有员工姓名，及其上级领导姓名。
SELECT E1.ENAME, E2.ENAME FROM EMP E1 JOIN EMP E2 ON E1.EMPNO = E2.MGR;